// bridge/bridge_state.cpp
// AUTO-GENERATED by scripts/generate_bridge_state.py
// from docs/superpowers/specs/2026-03-12-ftl-rl-observation-space.yaml
//
// FIXME_ACCESSOR markers indicate fields needing manual C++ access paths.
// These will cause compilation to fail until resolved.
//
// Sections follow CANONICAL ORDER from spec.py top_section_keys.
// Unimplemented sections advance idx to maintain correct field positions.
//
// Regenerate: python scripts/generate_bridge_state.py > bridge/bridge_state.cpp

#include "bridge.h"
#include <cstring>

namespace ftl_rl {

void Bridge::serializeState(float* buf, ShipManager* player,
                            ShipManager* enemy, SpaceManager* space) {
    // B.1 stub: zero-fill entire buffer.
    // B.2 will replace with real accessors (164 FIXME_ACCESSORs).
    (void)player; (void)enemy; (void)space;
    memset(buf, 0, STATE_BUFFER_BYTES);

#if 0 // ---- B.2: real serialization ----
    size_t idx = 0;

    // --- player_resources (4 fields) ---
    buf[idx++] = static_cast<float>(player->currentScrap); // scrap
    buf[idx++] = static_cast<float>(player->fFuel); // fuel
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponSystem.missile_count */); // missiles
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* DroneSystem.drone_count */); // drone_parts

    // --- player_ship (25 fields) ---
    buf[idx++] = static_cast<float>(player->ship.hullIntegrity.first); // hull_current
    buf[idx++] = static_cast<float>(player->ship.hullIntegrity.second); // hull_max
    buf[idx++] = static_cast<float>(player->shieldSystem->shields.power.first); // shield_layers
    buf[idx++] = static_cast<float>(player->shieldSystem->shields.charger); // shield_charge
    buf[idx++] = static_cast<float>(player->shieldSystem->chargeTime); // shield_charge_time_base
    buf[idx++] = static_cast<float>(player->shieldSystem->shields_shutdown); // shields_shutdown
    buf[idx++] = static_cast<float>(player->shieldSystem->bExcessChargeHack); // shield_excess_charge_hack
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Shields.Shield.power.super.first */); // super_shield_hp
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Shields.Shield.power.super.second */); // super_shield_max
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Shields.Shield.superTimer */); // super_shield_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipManager.evadeChance (base) */); // evade_chance_raw
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipManager.GetDodgeFactor() */); // effective_evade_chance
    buf[idx++] = static_cast<float>(player->failedDodgeCounter); // failed_dodge_counter
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* PowerManager.currentPower.second */); // reactor_total
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* PowerManager.currentPower.first */); // reactor_used
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: total - used */); // reactor_free
    buf[idx++] = static_cast<float>(player->iTempPowerLoss); // power_temp_loss
    buf[idx++] = static_cast<float>(player->iTempPowerCap); // power_temp_cap
    buf[idx++] = static_cast<float>(player->over_powered); // power_overpowered
    buf[idx++] = static_cast<float>(player->oxygenSystem->fTotalOxygen); // total_oxygen_percentage
    buf[idx++] = static_cast<float>(player->oxygenSystem->bLeakingO2); // is_leaking_o2
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from WorldManager/CApp state */); // game_phase
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: any crew with current_ship_id == enemy */); // has_boarders_on_enemy
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ArtillerySystem.ProjectileFactory.cooldown (ratio) */); // artillery_charge_progress
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ArtillerySystem.ProjectileFactory.cooldown.second */); // artillery_cooldown_base

    // --- systems (15 slots × 11 fields = 165) ---
    for (int i = 0; i < 15; i++) {
        // FIXME_ACCESSOR: get item pointer for systems[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 11 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipSystem.powerState.first */); // power_allocated
        buf[idx++] = static_cast<float>(sys->maxLevel); // max_level
        buf[idx++] = static_cast<float>(sys->healthState); // physical_damage
        buf[idx++] = static_cast<float>(sys->iLockCount); // ion_damage
        buf[idx++] = static_cast<float>(sys->lockTimer); // ion_timer
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: allocated - physical_damage - ion_damage + zoltan_power */); // effective_power
        buf[idx++] = static_cast<float>(sys->iHackEffect); // is_hacked
        buf[idx++] = static_cast<float>(item->hackingSystem->effectTimer); // hack_duration_remaining
        buf[idx++] = static_cast<float>(sys->fRepairOverTime); // repair_progress
        buf[idx++] = static_cast<float>(sys->iActiveManned); // active_manned_level
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // system_present
    }
    // Extra fields: medbay_clonebay_type_flag
    // FIXME_ACCESSOR: serialize 1 extra systems fields
    idx += 1;

    // --- cloaking (5 fields) ---
    buf[idx++] = static_cast<float>(player->cloakSystem->bTurnedOn); // cloak_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CloakingSystem.timer.currTime */); // cloak_timer_remaining
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CloakingSystem.timer.currGoal */); // cloak_timer_goal
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from system charge */); // cloak_cooldown_remaining
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* tracking counter */); // cloak_weapons_fired_during

    // --- hacking (12 fields) ---
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* HackingSystem.bArmed (inverted after launch) */); // hacking_drone_launched
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* HackingDrone state: launched but not arrived */); // hacking_drone_in_transit
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* HackingDrone.arrived */); // hacking_drone_arrived
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* HackingDrone.position */); // hacking_drone_position_x
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* HackingDrone.position */); // hacking_drone_position_y
    buf[idx++] = static_cast<float>(player->hackingSystem->bArmed); // hacking_armed
    buf[idx++] = static_cast<float>(player->hackingSystem->bCanHack); // hacking_can_hack
    buf[idx++] = static_cast<float>(player->hackingSystem->bBlocked); // hacking_blocked_by_supershield
    buf[idx++] = static_cast<float>(player->hackingSystem->currentSystem); // hacking_target_system_id
    buf[idx++] = static_cast<float>(player->hackingSystem->bHacking); // hacking_effect_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* HackingSystem.effectTimer.first */); // hacking_effect_timer_current
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* HackingSystem.effectTimer.second */); // hacking_effect_timer_goal

    // --- mind_control (6 fields) ---
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from controlTimer */); // mind_control_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* MindSystem.controlTimer.first */); // mind_control_timer_current
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* MindSystem.controlTimer.second */); // mind_control_timer_goal
    buf[idx++] = static_cast<float>(player->mindSystem->iArmed); // mind_control_armed
    buf[idx++] = static_cast<float>(player->mindSystem->bCanUse); // mind_control_can_use
    buf[idx++] = static_cast<float>(player->mindSystem->bSuperShields); // mind_control_blocked_by_supershield

    // --- teleporter (6 fields) ---
    buf[idx++] = static_cast<float>(player->teleportSystem->chargeLevel); // teleporter_charge_level
    buf[idx++] = static_cast<float>(player->teleportSystem->bCanSend); // teleporter_can_send
    buf[idx++] = static_cast<float>(player->teleportSystem->bCanReceive); // teleporter_can_receive
    buf[idx++] = static_cast<float>(player->teleportSystem->bSuperShields); // teleporter_blocked_by_supershield
    buf[idx++] = static_cast<float>(player->teleportSystem->iArmed); // teleporter_armed
    buf[idx++] = static_cast<float>(player->teleportSystem->iPreparedCrew); // teleporter_prepared_crew_count

    // --- battery (4 fields) ---
    buf[idx++] = static_cast<float>(player->batterySystem->bTurnedOn); // battery_active
    buf[idx++] = static_cast<float>(player->batterySystem->timer); // battery_timer_remaining
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BatterySystem power level */); // battery_power_provided
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from system */); // battery_cooldown_remaining

    // --- weapons (4 slots × 34 fields = 136) ---
    for (int i = 0; i < 4; i++) {
        // FIXME_ACCESSOR: get item pointer for weapons[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 34 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // weapon_present
        buf[idx++] = static_cast<float>(wpn->blueprint->type); // type
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from blueprint */); // subtype
        buf[idx++] = static_cast<float>(wpn->blueprint->power); // power_cost
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ProjectileFactory.cooldown (ratio) */); // charge_progress
        buf[idx++] = static_cast<float>(wpn->chargeLevel); // charge_level
        buf[idx++] = static_cast<float>(wpn->goalChargeLevel); // goal_charge_level
        buf[idx++] = static_cast<float>(wpn->boostLevel); // boost_level
        buf[idx++] = static_cast<float>(wpn->powered); // powered
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ProjectileFactory.cooldown when depowered */); // retained_charge
        buf[idx++] = static_cast<float>(wpn->blueprint->cooldown); // cooldown_base
        buf[idx++] = static_cast<float>(wpn->cooldownModifier); // cooldown_modifier
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.iDamage */); // damage
        buf[idx++] = static_cast<float>(wpn->blueprint->shots); // shots
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.fireChance */); // fire_chance
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.breachChance */); // breach_chance
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.iIonDamage */); // ion_damage
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.iSystemDamage */); // system_damage
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.iPersDamage */); // personnel_damage
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.iShieldPiercing */); // shield_piercing
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.bHullBust */); // hull_bust
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.stunChance */); // stun_chance
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.iStun */); // stun_duration
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WeaponBlueprint.damage.bLockdown */); // lockdown
        buf[idx++] = static_cast<float>(wpn->autoFiring); // autofire
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ProjectileFactory target */); // target_room
        buf[idx++] = static_cast<float>(wpn->blueprint->missiles); // costs_missile
        buf[idx++] = static_cast<float>(wpn->iAmmo); // weapon_ammo_remaining
        buf[idx++] = static_cast<float>(wpn->blueprint->drone_targetable); // weapon_drone_targetable
        buf[idx++] = static_cast<float>(wpn->isArtillery); // weapon_is_artillery
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ProjectileFactory.subCooldown.first */); // sub_cooldown_current
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ProjectileFactory.subCooldown.second */); // sub_cooldown_goal
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BeamProjectileInfo.swathStartX/Y derived */); // beam_entry_angle
        buf[idx++] = static_cast<float>(wpn->blueprint->length); // beam_length
    }

    // --- crew (32 slots × 42 fields = 1344) ---
    for (int i = 0; i < 32; i++) {
        // FIXME_ACCESSOR: get item pointer for crew[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 42 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // slot_occupied
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.health.first */); // hp
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.health.second */); // max_hp
        buf[idx++] = static_cast<float>(crew->healthBoost); // health_boost
        buf[idx++] = static_cast<float>(crew->iRoomId); // room_id
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.path target */); // target_room
        buf[idx++] = static_cast<float>(crew->currentShipId); // current_ship_id
        buf[idx++] = static_cast<float>(crew->species); // species
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: species==zoltan */); // provides_room_power
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewBlueprint.moveSpeed (normalized) */); // move_speed
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewBlueprint.repairSpeed (normalized) */); // repair_speed
        buf[idx++] = static_cast<float>(crew->blueprint->damageMultiplier); // damage_multiplier
        buf[idx++] = static_cast<float>(crew->blueprint->canSuffocate); // can_suffocate
        buf[idx++] = static_cast<float>(crew->blueprint->canBurn); // can_burn
        buf[idx++] = static_cast<float>(crew->blueprint->isTelepathic); // is_telepathic
        buf[idx++] = static_cast<float>(crew->blueprint->canPhaseThroughDoors); // can_phase_through_doors
        buf[idx++] = static_cast<float>(crew->blueprint->resistsMindControl); // resists_mind_control
        buf[idx++] = static_cast<float>(crew->bManning); // is_manning
        buf[idx++] = static_cast<float>(crew->iManningId); // manning_system
        buf[idx++] = static_cast<float>(crew->bRepairing); // is_repairing
        buf[idx++] = static_cast<float>(crew->bFighting); // is_fighting
        buf[idx++] = static_cast<float>(crew->intruder); // is_boarder
        buf[idx++] = static_cast<float>(crew->bDead); // is_dead
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.skillLevel[0] */); // skill_pilot
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.skillLevel[1] */); // skill_engines
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.skillLevel[2] */); // skill_shields
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.skillLevel[3] */); // skill_weapons
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.skillLevel[4] */); // skill_repair
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CrewMember.skillLevel[5] */); // skill_combat
        buf[idx++] = static_cast<float>(crew->bStunned); // is_stunned
        buf[idx++] = static_cast<float>(crew->fStunTime); // stun_timer
        buf[idx++] = static_cast<float>(crew->bFrozen); // is_frozen
        buf[idx++] = static_cast<float>(crew->fFrozenTime); // frozen_timer
        buf[idx++] = static_cast<float>(crew->bMindControlled); // is_mind_controlled
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from MindSystem timer */); // mind_control_duration
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from room O2 */); // is_suffocating
        buf[idx++] = static_cast<float>(crew->iOnFire); // is_on_fire
        buf[idx++] = static_cast<float>(crew->crewTarget); // melee_target_id
        buf[idx++] = static_cast<float>(crew->clone_ready); // clone_ready
        buf[idx++] = static_cast<float>(crew->fCloneDying); // clone_dying_timer
        buf[idx++] = static_cast<float>(crew->fMindDamageBoost); // mind_damage_boost
        buf[idx++] = static_cast<float>(crew->fLockdownTimer); // lockdown_ability_cooldown
    }

    // --- rooms (40 slots × 11 fields = 440) ---
    for (int i = 0; i < 40; i++) {
        // FIXME_ACCESSOR: get item pointer for rooms[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 11 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // room_active
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* OxygenSystem.oxygenLevels[room] */); // oxygen_level
        buf[idx++] = static_cast<float>(room->iFireCount); // fire_count
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: avg Fire.fDeathTimer */); // fire_avg_death_timer
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: avg Fire.fStartTimer */); // fire_avg_spread_timer
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: count breaches in room */); // breach_count
        buf[idx++] = static_cast<float>(room->iSystemId); // system_id
        buf[idx++] = static_cast<float>(room->bLockdown); // lockdown_active
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* LockdownShard.lifeTime */); // lockdown_timer
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Room tile count */); // room_size
        buf[idx++] = static_cast<float>(room->bStunning); // is_stunning
    }

    // --- enemy_room_positions (20 slots × 4 fields = 80) ---
    for (int i = 0; i < 20; i++) {
        // FIXME_ACCESSOR: get item pointer for enemy_room_positions[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 4 fields; continue; }
        buf[idx++] = static_cast<float>(room->rect.x); // room_x
        buf[idx++] = static_cast<float>(room->rect.y); // room_y
        buf[idx++] = static_cast<float>(room->rect.w); // room_width
        buf[idx++] = static_cast<float>(room->rect.h); // room_height
    }

    // --- doors (60 slots × 9 fields = 540) ---
    for (int i = 0; i < 60; i++) {
        // FIXME_ACCESSOR: get item pointer for doors[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 9 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // door_active
        buf[idx++] = static_cast<float>(door->health); // health
        buf[idx++] = static_cast<float>(door->baseHealth); // max_health
        buf[idx++] = static_cast<float>(door->bOpen); // is_open
        buf[idx++] = static_cast<float>(door->forcedOpen); // forced_open
        buf[idx++] = static_cast<float>(door->bIoned); // is_ioned
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Door.room connections */); // connects_room_a
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Door.room connections */); // connects_room_b
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Door.lockedDown timer */); // door_lockdown_timer
    }

    // --- ship_topology (800 fields) ---
    // FIXME_ACCESSOR: implement ship_topology serialization
    idx += 800;

    // --- drones (8 slots × 10 fields = 80) ---
    for (int i = 0; i < 8; i++) {
        // FIXME_ACCESSOR: get item pointer for drones[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 10 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // drone_present
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* DroneBlueprint.power */); // power_cost
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* DroneBlueprint.type */); // type
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceDrone.position */); // position_x
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceDrone.position */); // position_y
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceDrone.currentTarget */); // target_id
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceDrone.weaponCooldown */); // weapon_cooldown
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Drone.bDead */); // is_destroyed
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceDrone.bDisrupted */); // is_ion_disrupted
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceDrone.ionStun */); // ion_stun_timer
    }

    // --- augments (3 slots × 3 fields = 9) ---
    for (int i = 0; i < 3; i++) {
        // FIXME_ACCESSOR: get item pointer for augments[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 3 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // augment_present
        buf[idx++] = static_cast<float>(item->augments); // augment_id
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived: floor(blueprint.cost / 2) */); // sell_value
    }
    // Extra fields: effect_fields (titanium_casing, long_ranged_scanners, etc.)
    // FIXME_ACCESSOR: serialize 11 extra augments fields
    idx += 11;

    // --- environmental (17 fields) ---
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.bAsteroids */); // asteroid_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* AsteroidGenerator.iState */); // asteroid_phase
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* AsteroidGenerator.fStateTimer */); // asteroid_phase_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* AsteroidGenerator.timer */); // asteroid_next_spawn_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.nebula */); // nebula_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.sunLevel */); // solar_flare_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.sunTimer */); // solar_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.pulsar */); // pulsar_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.pulsarTimer */); // pulsar_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* StatusEffect TYPE_DIVIDE */); // plasma_storm_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.bPDS (ASB variant) */); // asb_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.pdsFireTimer */); // asb_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.envTarget */); // asb_target
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.bPDS */); // pds_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.pdsFireTimer */); // pds_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.envTarget */); // pds_target
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* SpaceManager.pdsCountdown */); // pds_countdown

    // --- combat_meta (27 fields) ---
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CombatControl.fCombatTimer */); // combat_time_elapsed
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipAI.escaping */); // enemy_fleeing
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipAI.escapeTimer */); // enemy_escape_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from escape timer */); // enemy_ftl_charge_progress
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipAI.surrenderThreshold */); // enemy_surrender_threshold
    buf[idx++] = static_cast<float>(enemy->bAutomated); // enemy_automated
    buf[idx++] = static_cast<float>(enemy->bInvincible); // enemy_invincible
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* event state */); // surrender_offer_active
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* surrender event reward */); // surrender_offer_scrap
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* surrender event reward */); // surrender_offer_fuel
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* surrender event reward */); // surrender_offer_missiles
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* surrender event reward */); // surrender_offer_drones
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* surrender event reward */); // surrender_offer_weapon_id
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* surrender event reward */); // surrender_offer_augment_id
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* surrender event reward */); // surrender_offer_crew_race
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipManager.jump_timer.first */); // ftl_charge_current
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipManager.jump_timer.second */); // ftl_charge_max
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* StarMap.worldLevel */); // sector_number
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* StarMap.currentSector.type */); // sector_type
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* WorldManager.difficulty */); // difficulty
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* ShipAI.bBoss */); // boss_fight
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BossShip.currentStage */); // boss_phase
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BossShip.nextStage */); // boss_next_phase
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BossShip.powerTimer.currTime */); // boss_power_surge_timer
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BossShip.powerTimer.currGoal */); // boss_power_surge_goal
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BossShip.powerCount */); // boss_power_surge_count
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* BossShip.bDeathBegan */); // boss_death_began

    // --- projectiles (16 slots × 13 fields = 208) ---
    for (int i = 0; i < 16; i++) {
        // FIXME_ACCESSOR: get item pointer for projectiles[i]
        // auto* item = player->FIXME_GET_ITEM(i);
        // if (item == nullptr) { zero-fill 13 fields; continue; }
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived */); // projectile_active
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile type */); // type
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.position */); // position_x
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.position */); // position_y
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.target */); // target_room
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.damage.iDamage */); // damage
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.damage.iIonDamage */); // proj_ion_damage
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from type */); // is_missile
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.speed */); // speed
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* derived from position, speed, target */); // estimated_arrival_ticks
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.missed */); // missed
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.hitTarget */); // hit_target
        buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* Projectile.ownerId */); // owned_by_player
    }

    // --- sensor_masking (23 fields) ---
    // FIXME_ACCESSOR: implement sensor_masking serialization
    idx += 23;

    // --- strategic (1279 fields) ---
    // FIXME_ACCESSOR: implement strategic serialization
    idx += 1279;

    // --- clone_bay (3 fields) ---
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CloneSystem.clone != null */); // clone_in_progress
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CloneSystem.fTimeToClone / fTimeGoal */); // clone_progress
    buf[idx++] = static_cast<float>(FIXME_ACCESSOR /* CloneSystem.fDeathTime */); // clone_death_timer

    // --- enemy_ship (152 fields) ---
    // FIXME_ACCESSOR: implement enemy_ship serialization
    idx += 152;

    // --- beam_path_lookup (80 paths × 5 rooms = 400 fields) ---
    for (int p = 0; p < BEAM_PATH_COUNT; p++) {
        for (int r = 0; r < BEAM_PATH_ROOMS; r++) {
            buf[idx++] = static_cast<float>(beam_paths_[p][r]);
        }
    }

    // Verify field count matches spec
    // assert(idx == 5793); // uncomment for debug
    (void)idx; // suppress unused warning in release
#endif // B.2
}

} // namespace ftl_rl

